-- 游戏陪玩管理系统 - MySQL数据库表结构创建脚本

-- 1. 创建陪玩人员表 (TB_STAFF)
CREATE TABLE TB_STAFF (
    STAFF_ID INT AUTO_INCREMENT PRIMARY KEY,
    STAFF_NAME VARCHAR(50) NOT NULL,
    REAL_NAME VARCHAR(50),
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    AGE INT CHECK (AGE BETWEEN 18 AND 60),
    PHONE VARCHAR(20) UNIQUE NOT NULL,
    EMAIL VARCHAR(100),
    AVATAR_URL VARCHAR(500),
    SKILL_LEVEL VARCHAR(20) DEFAULT 'GOLD',
    SERVICE_TYPE VARCHAR(200),
    UNIT_PRICE DECIMAL(10,2) DEFAULT 0 CHECK (UNIT_PRICE >= 0),
    STATUS VARCHAR(20) DEFAULT '空闲' CHECK (STATUS IN ('空闲', '忙碌', '离线', '封禁')),
    TOTAL_ORDERS INT DEFAULT 0,
    TOTAL_INCOME DECIMAL(10,2) DEFAULT 0,
    AVG_SCORE DECIMAL(3,2) DEFAULT 5.00,
    CERT_STATUS VARCHAR(20) DEFAULT 'UNVERIFIED',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_LOGIN_TIME DATETIME,
    IS_DELETED CHAR(1) DEFAULT 'N'
);

-- 创建索引
CREATE INDEX IDX_STAFF_NAME ON TB_STAFF(STAFF_NAME);
CREATE INDEX IDX_STAFF_STATUS ON TB_STAFF(STATUS);
CREATE INDEX IDX_STAFF_SKILL ON TB_STAFF(SKILL_LEVEL);
CREATE INDEX IDX_STAFF_CREATE_TIME ON TB_STAFF(CREATE_TIME);

-- 2. 创建客户表 (TB_CUSTOMER)
CREATE TABLE TB_CUSTOMER (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NICKNAME VARCHAR(50),
    PHONE VARCHAR(20) UNIQUE NOT NULL,
    EMAIL VARCHAR(100),
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    AGE INT,
    AVATAR_URL VARCHAR(500),
    MEMBER_LEVEL VARCHAR(20) DEFAULT 'REGULAR',
    TOTAL_CONSUME DECIMAL(10,2) DEFAULT 0,
    ORDER_COUNT INT DEFAULT 0,
    BALANCE DECIMAL(10,2) DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('正常', '冻结', '注销')),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_LOGIN_TIME DATETIME,
    IS_DELETED CHAR(1) DEFAULT 'N'
);

-- 创建索引
CREATE INDEX IDX_CUSTOMER_USERNAME ON TB_CUSTOMER(USERNAME);
CREATE INDEX IDX_CUSTOMER_PHONE ON TB_CUSTOMER(PHONE);
CREATE INDEX IDX_CUSTOMER_STATUS ON TB_CUSTOMER(STATUS);
CREATE INDEX IDX_CUSTOMER_CREATE_TIME ON TB_CUSTOMER(CREATE_TIME);

-- 3. 创建订单表 (TB_ORDER)
CREATE TABLE TB_ORDER (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_NO VARCHAR(50) UNIQUE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    STAFF_ID INT NOT NULL,
    GAME_TYPE VARCHAR(50) NOT NULL,
    SERVICE_HOURS INT DEFAULT 1 CHECK (SERVICE_HOURS > 0),
    UNIT_PRICE DECIMAL(10,2) NOT NULL CHECK (UNIT_PRICE >= 0),
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    PLATFORM_COMMISSION DECIMAL(10,2) DEFAULT 0,
    STAFF_INCOME DECIMAL(10,2) DEFAULT 0,
    ORDER_STATUS VARCHAR(20) DEFAULT 'PENDING' 
        CHECK (ORDER_STATUS IN ('待支付', '已支付', '服务中', '已完成', '已取消', '退款中', '已退款')),
    PAY_TIME DATETIME,
    START_TIME DATETIME,
    END_TIME DATETIME,
    CUSTOMER_COMMENT VARCHAR(500),
    STAFF_COMMENT VARCHAR(500),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) DEFAULT 'N',
    FOREIGN KEY (CUSTOMER_ID) REFERENCES TB_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (STAFF_ID) REFERENCES TB_STAFF(STAFF_ID)
);

-- 创建索引
CREATE INDEX IDX_ORDER_NO ON TB_ORDER(ORDER_NO);
CREATE INDEX IDX_ORDER_CUSTOMER ON TB_ORDER(CUSTOMER_ID);
CREATE INDEX IDX_ORDER_STAFF ON TB_ORDER(STAFF_ID);
CREATE INDEX IDX_ORDER_STATUS ON TB_ORDER(ORDER_STATUS);

-- 4. 创建评价表 (TB_EVALUATION)
CREATE TABLE TB_EVALUATION (
    EVAL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    STAFF_ID INT NOT NULL,
    SCORE INT CHECK (SCORE BETWEEN 1 AND 5),
    CONTENT VARCHAR(500),
    TAGS VARCHAR(200),
    IS_ANONYMOUS CHAR(1) DEFAULT 'N',
    STAFF_REPLY VARCHAR(500),
    REPLY_TIME DATETIME,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) DEFAULT 'N',
    FOREIGN KEY (ORDER_ID) REFERENCES TB_ORDER(ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES TB_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (STAFF_ID) REFERENCES TB_STAFF(STAFF_ID)
);

-- 创建索引
CREATE INDEX IDX_EVAL_ORDER ON TB_EVALUATION(ORDER_ID);
CREATE INDEX IDX_EVAL_STAFF ON TB_EVALUATION(STAFF_ID);
CREATE INDEX IDX_EVAL_SCORE ON TB_EVALUATION(SCORE);
CREATE INDEX IDX_EVAL_CREATE_TIME ON TB_EVALUATION(CREATE_TIME);

-- 5. 创建投诉表 (TB_COMPLAINT)
CREATE TABLE TB_COMPLAINT (
    COMPLAINT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT,
    CUSTOMER_ID INT NOT NULL,
    STAFF_ID INT,
    COMPLAINT_TYPE VARCHAR(50) NOT NULL,
    COMPLAINT_CONTENT VARCHAR(1000) NOT NULL,
    EVIDENCE_URL VARCHAR(500),
    COMPLAINT_STATUS VARCHAR(20) DEFAULT 'PENDING' 
        CHECK (COMPLAINT_STATUS IN ('待处理', '处理中', '已解决', '已关闭')),
    HANDLER_ID INT,
    HANDLER_COMMENT VARCHAR(500),
    HANDLE_TIME DATETIME,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) DEFAULT 'N',
    FOREIGN KEY (ORDER_ID) REFERENCES TB_ORDER(ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES TB_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (STAFF_ID) REFERENCES TB_STAFF(STAFF_ID)
);

-- 创建索引
CREATE INDEX IDX_COMP_STATUS ON TB_COMPLAINT(COMPLAINT_STATUS);
CREATE INDEX IDX_COMP_CREATE_TIME ON TB_COMPLAINT(CREATE_TIME);

-- 6. 创建角色表 (TB_ROLE)
CREATE TABLE TB_ROLE (
    ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME VARCHAR(50) NOT NULL,
    ROLE_DESC VARCHAR(200),
    PERMISSIONS VARCHAR(2000),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) DEFAULT 'N'
);

-- 插入默认角色
INSERT INTO TB_ROLE (ROLE_NAME, ROLE_DESC, PERMISSIONS) VALUES 
('超级管理员', '拥有所有权限', 'all');

INSERT INTO TB_ROLE (ROLE_NAME, ROLE_DESC, PERMISSIONS) VALUES 
('运营管理员', '陪玩人员管理、订单管理', 'staff,order,evaluation');

INSERT INTO TB_ROLE (ROLE_NAME, ROLE_DESC, PERMISSIONS) VALUES 
('客服人员', '投诉处理、评价管理', 'complaint,evaluation');

INSERT INTO TB_ROLE (ROLE_NAME, ROLE_DESC, PERMISSIONS) VALUES 
('财务人员', '财务管理、提现审核', 'finance,withdraw');

INSERT INTO TB_ROLE (ROLE_NAME, ROLE_DESC, PERMISSIONS) VALUES 
('查看员', '仅查看权限', 'view');

-- 7. 创建管理员表 (TB_ADMIN)
CREATE TABLE TB_ADMIN (
    ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NICKNAME VARCHAR(50),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    ROLE_ID INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('正常', '冻结')),
    LAST_LOGIN_TIME DATETIME,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) DEFAULT 'N',
    FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE(ROLE_ID)
);

-- 创建索引
CREATE INDEX IDX_ADMIN_USERNAME ON TB_ADMIN(USERNAME);
CREATE INDEX IDX_ADMIN_ROLE ON TB_ADMIN(ROLE_ID);

-- 8. 创建数据字典表 (TB_DICTIONARY)
CREATE TABLE TB_DICTIONARY (
    DICT_ID INT AUTO_INCREMENT PRIMARY KEY,
    DICT_TYPE VARCHAR(50) NOT NULL,
    DICT_CODE VARCHAR(50) NOT NULL,
    DICT_VALUE VARCHAR(100) NOT NULL,
    DICT_DESC VARCHAR(200),
    SORT_ORDER INT DEFAULT 0,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) DEFAULT 'N',
    UNIQUE KEY UK_DICT_TYPE_CODE (DICT_TYPE, DICT_CODE)
);

-- 创建索引
CREATE INDEX IDX_DICT_TYPE ON TB_DICTIONARY(DICT_TYPE);

-- 插入游戏类型
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('GAME_TYPE', 'LOL', '英雄联盟', 1);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('GAME_TYPE', 'WZRY', '王者荣耀', 2);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('GAME_TYPE', 'HPJY', '和平精英', 3);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('GAME_TYPE', 'JDCQ', '绝地求生', 4);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('GAME_TYPE', 'DNF', '地下城与勇士', 5);

-- 插入技能等级
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('SKILL_LEVEL', 'BRONZE', '青铜', 1);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('SKILL_LEVEL', 'SILVER', '白银', 2);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('SKILL_LEVEL', 'GOLD', '黄金', 3);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('SKILL_LEVEL', 'PLATINUM', '铂金', 4);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('SKILL_LEVEL', 'DIAMOND', '钻石', 5);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('SKILL_LEVEL', 'MASTER', '王者', 6);

-- 插入投诉类型
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('COMPLAINT_TYPE', 'ATTITUDE', '服务态度', 1);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('COMPLAINT_TYPE', 'QUALITY', '服务质量', 2);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('COMPLAINT_TYPE', 'PRICE', '收费问题', 3);
INSERT INTO TB_DICTIONARY (DICT_TYPE, DICT_CODE, DICT_VALUE, SORT_ORDER) VALUES ('COMPLAINT_TYPE', 'OTHER', '其他', 4);

-- 9. 创建操作日志表 (TB_OPERATION_LOG)
CREATE TABLE TB_OPERATION_LOG (
    LOG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_ID INT,
    ADMIN_NAME VARCHAR(50),
    OPERATION_TYPE VARCHAR(50),
    OPERATION_DESC VARCHAR(500),
    REQUEST_URL VARCHAR(200),
    REQUEST_METHOD VARCHAR(20),
    REQUEST_IP VARCHAR(50),
    REQUEST_PARAMS VARCHAR(2000),
    RESPONSE_RESULT VARCHAR(2000),
    EXECUTE_TIME INT,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED CHAR(1) DEFAULT 'N',
    FOREIGN KEY (ADMIN_ID) REFERENCES TB_ADMIN(ADMIN_ID)
);

-- 创建索引
CREATE INDEX IDX_LOG_ADMIN ON TB_OPERATION_LOG(ADMIN_ID);
CREATE INDEX IDX_LOG_CREATE_TIME ON TB_OPERATION_LOG(CREATE_TIME);
CREATE INDEX IDX_LOG_OPERATION_TYPE ON TB_OPERATION_LOG(OPERATION_TYPE);