-- 提现管理测试数据插入脚本
-- 为提现管理功能创建测试数据

-- 1. 首先确保有已完成的订单来生成收入
UPDATE TB_ORDER 
SET 
  ORDER_STATUS = '已完成',
  PAY_TIME = CASE 
    WHEN PAY_TIME IS NULL THEN DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 10) DAY)
    ELSE PAY_TIME
  END
WHERE IS_DELETED = 'N' 
  AND ORDER_STATUS IN ('待支付', '已支付', '服务中')
  AND ORDER_ID % 2 = 0  -- 只更新一半的订单为已完成状态
LIMIT 50;

-- 2. 更新订单的财务字段（平台抽成和陪玩收入）
UPDATE TB_ORDER 
SET 
  PLATFORM_COMMISSION = CASE 
    WHEN ORDER_STATUS = '已完成' THEN TOTAL_AMOUNT * 0.2 
    ELSE 0 
  END,
  STAFF_INCOME = CASE 
    WHEN ORDER_STATUS = '已完成' THEN TOTAL_AMOUNT * 0.8 
    ELSE 0 
  END
WHERE IS_DELETED = 'N';

-- 3. 更新陪玩人员的总收入和订单数（基于已完成订单）
UPDATE TB_STAFF s
JOIN (
  SELECT 
    STAFF_ID,
    SUM(STAFF_INCOME) AS total_income,
    COUNT(*) AS total_orders
  FROM TB_ORDER 
  WHERE ORDER_STATUS = '已完成' 
    AND IS_DELETED = 'N'
  GROUP BY STAFF_ID
) o ON s.STAFF_ID = o.STAFF_ID
SET 
  s.TOTAL_INCOME = o.total_income,
  s.TOTAL_ORDERS = o.total_orders;

-- 4. 为部分陪玩人员设置更高的收入以模拟可提现金额
UPDATE TB_STAFF 
SET 
  TOTAL_INCOME = CASE 
    WHEN TOTAL_INCOME < 1000 THEN TOTAL_INCOME + 1000 + FLOOR(RAND() * 2000)  -- 确保收入大于1000元
    ELSE TOTAL_INCOME
  END,
  TOTAL_ORDERS = CASE 
    WHEN TOTAL_ORDERS = 0 THEN FLOOR(RAND() * 10) + 1
    ELSE TOTAL_ORDERS
  END
WHERE IS_DELETED = 'N' 
  AND STAFF_ID IN (
    SELECT DISTINCT STAFF_ID 
    FROM TB_ORDER 
    WHERE ORDER_STATUS = '已完成' 
    LIMIT 20
  );

-- 5. 插入一些测试数据确保有足够的可提现记录
-- 为没有收入的陪玩人员创建一些已完成订单
INSERT INTO TB_ORDER (
  ORDER_NO, CUSTOMER_ID, STAFF_ID, GAME_TYPE, SERVICE_HOURS, 
  UNIT_PRICE, TOTAL_AMOUNT, ORDER_STATUS, PAY_TIME, CREATE_TIME, IS_DELETED
)
SELECT 
  CONCAT('ORD', LPAD(FLOOR(RAND() * 1000000000) + 1000000000, 10, '0')) AS ORDER_NO,
  c.CUSTOMER_ID,
  s.STAFF_ID,
  CASE FLOOR(RAND() * 4) 
    WHEN 0 THEN '英雄联盟' 
    WHEN 1 THEN '王者荣耀' 
    WHEN 2 THEN '和平精英' 
    ELSE '绝地求生' 
  END AS GAME_TYPE,
  FLOOR(RAND() * 10) + 1 AS SERVICE_HOURS,
  FLOOR(RAND() * 200) + 50 AS UNIT_PRICE,
  (FLOOR(RAND() * 200) + 50) * (FLOOR(RAND() * 10) + 1) AS TOTAL_AMOUNT,
  '已完成' AS ORDER_STATUS,
  DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY) AS PAY_TIME,
  DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY) AS CREATE_TIME,
  'N' AS IS_DELETED
FROM TB_CUSTOMER c, TB_STAFF s
WHERE s.TOTAL_INCOME = 0 OR s.TOTAL_INCOME IS NULL
LIMIT 30;

-- 6. 再次更新财务数据以包含新增的订单
UPDATE TB_ORDER 
SET 
  PLATFORM_COMMISSION = TOTAL_AMOUNT * 0.2,
  STAFF_INCOME = TOTAL_AMOUNT * 0.8
WHERE IS_DELETED = 'N' 
  AND ORDER_STATUS = '已完成'
  AND PLATFORM_COMMISSION = 0;

-- 7. 再次更新陪玩人员的总收入和订单数
UPDATE TB_STAFF s
JOIN (
  SELECT 
    STAFF_ID,
    SUM(STAFF_INCOME) AS total_income,
    COUNT(*) AS total_orders
  FROM TB_ORDER 
  WHERE ORDER_STATUS = '已完成' 
    AND IS_DELETED = 'N'
  GROUP BY STAFF_ID
) o ON s.STAFF_ID = o.STAFF_ID
SET 
  s.TOTAL_INCOME = o.total_income,
  s.TOTAL_ORDERS = o.total_orders
WHERE s.IS_DELETED = 'N';

-- 8. 显示测试数据结果
SELECT 
  '提现测试数据插入完成' AS RESULT,
  (SELECT COUNT(*) FROM TB_STAFF WHERE IS_DELETED = 'N' AND TOTAL_INCOME > 0) AS staff_with_income,
  (SELECT COUNT(*) FROM TB_ORDER WHERE IS_DELETED = 'N' AND ORDER_STATUS = '已完成') AS completed_orders;