-- 测试数据插入总结报告
SET PAGESIZE 100
SET LINESIZE 200
COLUMN TABLE_NAME FORMAT A20
COLUMN COUNT FORMAT 999,999

-- 表记录数量统计
PROMPT === 数据表记录数量统计 ===
SELECT 'TB_ORDER' AS TABLE_NAME, COUNT(*) AS COUNT FROM TB_ORDER 
UNION ALL
SELECT 'TB_COMPLAINT' AS TABLE_NAME, COUNT(*) AS COUNT FROM TB_COMPLAINT 
UNION ALL
SELECT 'TB_STAFF' AS TABLE_NAME, COUNT(*) AS COUNT FROM TB_STAFF 
UNION ALL
SELECT 'TB_CUSTOMER' AS TABLE_NAME, COUNT(*) AS COUNT FROM TB_CUSTOMER;

PROMPT
PROMPT === 订单状态分布 ===
SELECT ORDER_STATUS, COUNT(*) AS COUNT FROM TB_ORDER GROUP BY ORDER_STATUS ORDER BY COUNT DESC;

PROMPT
PROMPT === 投诉状态分布 ===
SELECT COMPLAINT_STATUS, COUNT(*) AS COUNT FROM TB_COMPLAINT GROUP BY COMPLAINT_STATUS ORDER BY COUNT DESC;

PROMPT
PROMPT === 投诉类型分布 ===
SELECT COMPLAINT_TYPE, COUNT(*) AS COUNT FROM TB_COMPLAINT GROUP BY COMPLAINT_TYPE ORDER BY COUNT DESC;

PROMPT
PROMPT === 财务统计信息 ===
SELECT 
  COUNT(*) AS TOTAL_ORDERS,
  SUM(CASE WHEN ORDER_STATUS = UNISTR('\5DF2\5B8C\6210') THEN 1 ELSE 0 END) AS COMPLETED_ORDERS,
  SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
  SUM(PLATFORM_COMMISSION) AS PLATFORM_INCOME,
  SUM(STAFF_INCOME) AS STAFF_TOTAL_INCOME
FROM TB_ORDER;

PROMPT
PROMPT === 陪玩人员财务统计 ===
SELECT 
  COUNT(*) AS TOTAL_STAFF,
  AVG(TOTAL_INCOME) AS AVG_INCOME,
  AVG(TOTAL_ORDERS) AS AVG_ORDERS,
  AVG(AVG_SCORE) AS AVG_RATING
FROM TB_STAFF 
WHERE TOTAL_INCOME > 0 OR TOTAL_ORDERS > 0;

PROMPT
PROMPT === 数据插入完成！订单投诉和财务管理数据已准备就绪 ===