-- 更新陪玩人员的订单数和收入（基于订单数据）- MySQL版本

-- 更新陪玩人员的订单数和收入（基于订单数据）
UPDATE TB_STAFF SET 
  TOTAL_ORDERS = (
    SELECT COUNT(*) 
    FROM TB_ORDER 
    WHERE TB_ORDER.STAFF_ID = TB_STAFF.STAFF_ID 
    AND TB_ORDER.ORDER_STATUS = '已完成'
    AND TB_ORDER.IS_DELETED = 'N'
  ),
  TOTAL_INCOME = (
    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0) 
    FROM TB_ORDER 
    WHERE TB_ORDER.STAFF_ID = TB_STAFF.STAFF_ID 
    AND TB_ORDER.ORDER_STATUS = '已完成'
    AND TB_ORDER.IS_DELETED = 'N'
  );

-- 更新客户的订单数和消费金额（基于订单数据）
UPDATE TB_CUSTOMER SET 
  ORDER_COUNT = (
    SELECT COUNT(*) 
    FROM TB_ORDER 
    WHERE TB_ORDER.CUSTOMER_ID = TB_CUSTOMER.CUSTOMER_ID
    AND TB_ORDER.IS_DELETED = 'N'
  ),
  TOTAL_CONSUME = (
    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0) 
    FROM TB_ORDER 
    WHERE TB_ORDER.CUSTOMER_ID = TB_CUSTOMER.CUSTOMER_ID
    AND TB_ORDER.IS_DELETED = 'N'
  );

-- 显示各表数据统计
SELECT 'TB_STAFF统计:' AS table_info, COUNT(*) AS count FROM TB_STAFF
UNION ALL
SELECT 'TB_CUSTOMER统计:' AS table_info, COUNT(*) AS count FROM TB_CUSTOMER
UNION ALL
SELECT 'TB_ORDER统计:' AS table_info, COUNT(*) AS count FROM TB_ORDER
UNION ALL
SELECT 'TB_EVALUATION统计:' AS table_info, COUNT(*) AS count FROM TB_EVALUATION
UNION ALL
SELECT 'TB_COMPLAINT统计:' AS table_info, COUNT(*) AS count FROM TB_COMPLAINT;