-- 更新财务数据，确保提现管理功能有测试数据

-- 1. 确保已完成订单的财务字段正确
UPDATE TB_ORDER 
SET 
  PLATFORM_COMMISSION = TOTAL_AMOUNT * 0.2,
  STAFF_INCOME = TOTAL_AMOUNT * 0.8
WHERE ORDER_STATUS = '已完成' 
  AND IS_DELETED = 'N'
  AND (PLATFORM_COMMISSION = 0 OR STAFF_INCOME = 0);

-- 2. 更新陪玩人员的总收入和订单数
UPDATE TB_STAFF s
SET 
  TOTAL_INCOME = (
    SELECT COALESCE(SUM(STAFF_INCOME), 0) 
    FROM TB_ORDER 
    WHERE STAFF_ID = s.STAFF_ID 
      AND ORDER_STATUS = '已完成' 
      AND IS_DELETED = 'N'
  ),
  TOTAL_ORDERS = (
    SELECT COUNT(*) 
    FROM TB_ORDER 
    WHERE STAFF_ID = s.STAFF_ID 
      AND ORDER_STATUS = '已完成' 
      AND IS_DELETED = 'N'
  )
WHERE s.IS_DELETED = 'N';

-- 3. 验证数据更新结果
SELECT 
  '财务数据更新完成' AS RESULT,
  (SELECT COUNT(*) FROM TB_STAFF WHERE IS_DELETED = 'N' AND TOTAL_INCOME > 0) AS staff_with_income,
  (SELECT COUNT(*) FROM TB_ORDER WHERE IS_DELETED = 'N' AND ORDER_STATUS = '已完成') AS completed_orders,
  (SELECT COUNT(*) FROM TB_ORDER WHERE IS_DELETED = 'N' AND ORDER_STATUS = '已完成' AND (PLATFORM_COMMISSION = 0 OR STAFF_INCOME = 0)) AS orders_with_zero_income;